"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def fib(term1, term2, total):
    next_term = term1 + term2
    if next_term % 2 == 0:
        total = total + next_term
    if total < 4000000:
        fib(term2, next_term, total)
    else:
        print(total - 1)


fib(1, 2, 3)
